### ISSUE TITLE
problemas menu

### ISSUE THREAD

**Issue by if-pascual** [curso-github-cefire/plantilla-jekyll#120]
Tengo creada las dos páginas pero no las enlaza.

Gracias

**Comment by pedroprieto** [comment]
Buenas,

El issue debes crearlo en tu repositorio. Si no están activos, accede a los `Settings` del repositorio y actívalos: 

![imagen](https://github.com/curso-github-cefire/plantilla-jekyll/assets/7632447/49e70209-b1ad-4373-9c94-e874d990f8cf)

En cualquier caso, te contesto por aquí. Te falta un guión `-` en la primera línea de este archivo:
https://github.com/if-pascual/plantilla-jekyll/blob/ac41c6352eeb8015fe29b432d546792515d39e01/blog.html#L1

Un saludo!!

**Comment by if-pascual** [comment]
Nuevamente, muchas gracias por la aclaración y la ayuda. Ya he modificado el guión.

¿estaría bien creado el issue?
________________________________
De: Pedro Prieto ***@***.***>
Enviado: martes, 6 de febrero de 2024 10:48
Para: curso-github-cefire/plantilla-jekyll ***@***.***>
Cc: BAÑO ALBARRÁN, PASCUAL ***@***.***>; Author ***@***.***>
Asunto: Re: [curso-github-cefire/plantilla-jekyll] problemas menu (Issue #120)


Closed #120<https://github.com/curso-github-cefire/plantilla-jekyll/issues/120> as completed.

**Comment by pedroprieto** [comment]
Sin problema :blush: 

Te contesto por el otro issue. Te ha faltado nombrarme :wink:
